services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VITE_API_URI: ${VITE_API_URI}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - ../app-ui/.env